# ================================================================================
# FILE: sqlserver.tf
# ================================================================================
# PURPOSE:
#   Deploys a private Cloud SQL for SQL Server instance and publishes a private
#   DNS record for consistent internal name resolution.
#
# RESOURCES:
#   - Cloud SQL instance (SQL Server 2022 Standard) on private IP only
#   - Private DNS managed zone scoped to the SQL Server VPC
#   - Private A record mapping sqlserver.internal.* to the instance private IP
#   - Creation guard to allow VPC peering propagation before Cloud SQL creation
#
# NOTES:
#   - This build disables public IPv4 and relies on Private Service Access
#   - deletion_protection is disabled to allow terraform destroy in labs
#   - The null_resource sleep is a pragmatic guard for peering propagation
# ================================================================================

# ================================================================================
# CLOUD SQL INSTANCE: SQL SERVER 2022 STANDARD
# ================================================================================
# - Provisions a Cloud SQL SQL Server instance in us-central1
# - Uses private IP connectivity only (no public IPv4)
# - Root password is generated by random_password and stored in Secret Manager
# ================================================================================

resource "google_sql_database_instance" "sqlserver" {
  name             = "sqlserver-instance"
  database_version = "SQLSERVER_2022_EXPRESS"
  region           = "us-central1"
  root_password    = random_password.sqlserver.result

  settings {
    tier = "db-custom-1-3840"

    ip_configuration {
      ipv4_enabled    = false
      private_network = google_compute_network.sqlserver_vpc.self_link
    }

    backup_configuration {
      enabled = true
    }

    maintenance_window {
      day          = 7
      hour         = 3
      update_track = "stable"
    }

    activation_policy  = "ALWAYS"
    availability_type  = "ZONAL"
  }

  deletion_protection = false

  depends_on = [
    null_resource.wait_for_vpc_peering
  ]
}

# ================================================================================
# PRIVATE DNS ZONE
# ================================================================================
# - Creates a private DNS zone for internal SQL Server name resolution
# - Zone visibility is restricted to the SQL Server VPC
# ================================================================================

resource "google_dns_managed_zone" "private_dns" {
  name       = "internal-sqlserver-zone"
  dns_name   = "internal.sqlserver-zone.local."
  visibility = "private"

  private_visibility_config {
    networks {
      network_url = google_compute_network.sqlserver_vpc.id
    }
  }

  description = "Private DNS zone for internal SQL Server database"
}

# ================================================================================
# PRIVATE DNS RECORD: SQLSERVER
# ================================================================================
# - Publishes sqlserver.internal.sqlserver-zone.local to the Cloud SQL private IP
# - Provides a stable endpoint for Adminer and other internal consumers
# ================================================================================

resource "google_dns_record_set" "sqlserver_dns" {
  name         = "sqlserver.internal.sqlserver-zone.local."
  type         = "A"
  ttl          = 300
  managed_zone = google_dns_managed_zone.private_dns.name

  rrdatas = [
    google_sql_database_instance.sqlserver.private_ip_address
  ]
}

# ================================================================================
# CREATION GUARD: WAIT FOR VPC PEERING
# ================================================================================
# - Service Networking peering can take time to propagate after creation
# - This guard reduces intermittent Cloud SQL creation failures
# ================================================================================

resource "null_resource" "wait_for_vpc_peering" {
  depends_on = [
    google_service_networking_connection.private_vpc_connection
  ]

  provisioner "local-exec" {
    command = "echo 'Waiting for VPC peering to propagate...' && sleep 300"
  }
}
